title: The Cersonsky Lab at UW-Madison
logo: /assets/img/logo.png
description: The Cersonsky Lab is a research group based at the University of Wisconsin - Madison, Department of Chemical and Biological Engineering
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
