name: PR Preview (docs/website)

on:
  pull_request:
    branches:
      - main  # Or your default branch

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Required for pushing

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Use your actual version

      - name: Install Jekyll dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site for preview
        run: bundle exec jekyll build --baseurl "/website/pr-preview/pr-${{ github.event.pull_request.number }}" --destination ./preview

      - name: Copy preview into docs folder
        run: |
          mkdir -p docs/website/pr-preview/pr-${{ github.event.pull_request.number }}
          rm -rf docs/website/pr-preview/pr-${{ github.event.pull_request.number }}/*
          cp -r preview/* docs/website/pr-preview/pr-${{ github.event.pull_request.number }}/

      - name: Commit preview
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/website/pr-preview/pr-${{ github.event.pull_request.number }}
          git commit -m "Add PR preview for #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push origin main

      - name: Comment preview link on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚀 Preview your site here:
            https://cersonsky-lab.github.io/website/pr-preview/pr-${{ github.event.pull_request.number }}
